//==========================================================================//
// 이 파일은 export_interface.lua 스크립트에 의해 자동생성된 코드입니다.
// 직접 수정하지 마십시오.
// 06/12/15 00:04:16
//==========================================================================//


ZL_FUNC_BEGIN( GF_ChangeState, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_DeleteEffectFromObject, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_EffectOnObject, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_GetEffectUseFile, RETURNS_INT )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_GetEffectUseIndex, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_GetMotionUseFile, RETURNS_INT )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_GetTarget, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_LogString, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_Random, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_SetMotion, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_WeatherEffectOnObject, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_addUserMoney, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_appraisal, RETURNS_NONE )
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_checkNumOfInvItem, RETURNS_INT )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_checkTownItem, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_checkUserMoney, RETURNS_INT )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_disorganizeClan, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_error, RETURNS_NONE )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getDate, RETURNS_STRING )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getGameVersion, RETURNS_STRING )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getIDXOfInvItem, RETURNS_INT )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getItemRate, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getName, RETURNS_STRING )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getReviveZoneName, RETURNS_STRING )
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getTownRate, RETURNS_INT )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getTownVar, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getVariable, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getWorldRate, RETURNS_INT )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_getZone, RETURNS_INT )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_giveEquipItemIntoInv, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT,
	         ZL_INT,
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_giveUsableItemIntoInv, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_log, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_movableXY, RETURNS_INT )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_moveEvent, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_moveXY, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_openBank, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_openDeliveryStore, RETURNS_NONE )
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_openSeparate, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_openStore, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_openUpgrade, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_organizeClan, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_playEffect, RETURNS_NONE )
	         ZL_INT,
	       ZL_FLOAT,
	       ZL_FLOAT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_playSound, RETURNS_NONE )
	      ZL_STRING,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_putoffItem, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_putonItem, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_repair, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_rotateCamera, RETURNS_NONE )
	         ZL_INT,
	       ZL_FLOAT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_setEquipedItem, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_setRevivePosition, RETURNS_NONE )
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_setTownRate, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_setVariable, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_setWorldRate, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_spawnMonAtEvent, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_spawnMonXY, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_takeItemFromInv, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_takeUserMoney, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_warp, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( GF_zoomCamera, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

// end of file
