/*
	$Header: /Client/Event/QF_SKILL.CPP 2     03-06-12 11:29a Icarus $
*/

#include "stdAFX.h"
#include "Quest_FUNC.h"

//-------------------------------------------------------------------------------------------------
int		QF_getSkillLevel ( int iSkillNo )
{
	return 0;
}

int		QF_givePoint ( int iPoint )
{
	return 0;
}


//-------------------------------------------------------------------------------------------------
