//==========================================================================//
// 이 파일은 export_interface.lua 스크립트에 의해 자동생성된 코드입니다.
// 직접 수정하지 마십시오.
// 06/12/15 00:04:16
//==========================================================================//


ZL_FUNC_BEGIN( QF_CameraworkingNpc, RETURNS_NONE )
	      ZL_STRING,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_CameraworkingPoint, RETURNS_NONE )
	      ZL_STRING,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_CameraworkingSelf, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_ChangetalkImage, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_ChangetalkName, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_EffectCallNpc, RETURNS_NONE )
	      ZL_STRING,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_EffectCallSelf, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_MotionCallNpc, RETURNS_NONE )
	      ZL_STRING,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_MotionCallSelf, RETURNS_NONE )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_NpcHide, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_NpcTalkinterfaceHide, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_NpcTalkinterfaceView, RETURNS_NONE )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_NpcView, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_appendQuest, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_beginCon, RETURNS_NONE )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_checkQuestCondition, RETURNS_INT )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_closeCon, RETURNS_NONE )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_deleteQuest, RETURNS_NONE )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_doQuestTrigger, RETURNS_INT )
	      ZL_STRING
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_findQuest, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getEpisodeVAR, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getEventOwner, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getJobVAR, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getNpcQuestZeroVal, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getPlanetVAR, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getQuestCount, RETURNS_INT )
	               
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getQuestID, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getQuestItemQuantity, RETURNS_INT )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getQuestSwitch, RETURNS_INT )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getQuestVar, RETURNS_INT )
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getSkillLevel, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getUnionVAR, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_getUserSwitch, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_givePoint, RETURNS_INT )
	         ZL_INT
ZL_FUNC_END

ZL_FUNC_BEGIN( QF_gotoCon, RETURNS_NONE )
	         ZL_INT,
	         ZL_INT,
	         ZL_INT
ZL_FUNC_END

// end of file
